import { AbsoluteFill, Audio, staticFile, useCurrentFrame } from 'remotion';
import { C, rise, tw, IN_OUT } from './theme.js';
import { T } from './timeline.js';
import { Wordmark } from './ui.jsx';
import { SceneHero } from './SceneHero.jsx';
import { SceneApp } from './SceneApp.jsx';
import { SceneNotes } from './SceneNotes.jsx';
import { SceneModes } from './SceneModes.jsx';
import { SceneTravel } from './SceneTravel.jsx';
import { SceneClose } from './SceneClose.jsx';

// Muesli, 50 s. Each scene draws only inside its own window of frames (see src/timeline.js).
export const Film = () => {
  const f = useCurrentFrame();
  // the small wordmark rides the top left until the slate rises over it
  const bug = { ...rise(f, T.wordmarkIn, 24, 0), opacity: tw(f, T.wordmarkIn, T.wordmarkIn + 24, 0, 1) * (1 - tw(f, T.slate - 6, T.slate + 14, 0, 1, IN_OUT)) };
  return (
    <AbsoluteFill style={{ backgroundColor: C.cream, overflow: 'hidden' }}>
      {/* original score, generated by scripts/sound.py from the same timeline */}
      <Audio src={staticFile('audio/score.wav')} />
      <div style={{ position: 'absolute', left: 96, top: 52, ...bug }}><Wordmark size={46} /></div>
      <SceneHero />
      <SceneApp />
      <SceneNotes />
      <SceneModes />
      <SceneTravel />
      <SceneClose />
    </AbsoluteFill>
  );
};
